version: "3.8"

networks:
  xyz-network:
    name: xyz-network
    driver: bridge

volumes:
  xyz-volume:
    name: xyz-volume

services:
  xyz-mysql:
    image: mysql:latest
    container_name: xyz-mysql
    restart: on-failure
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - xyz-network
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

  xyz-jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: xyz-jaeger
    networks:
      - xyz-network
    restart: on-failure
    ports:
      - target: 16686
        published: 16686
        protocol: tcp
        mode: host
      - target: 6831
        published: 6831
        protocol: udp
        mode: host
    depends_on:
      - xyz-mysql

  filebeat:
    image: docker.elastic.co/beats/filebeat:7.15.1
    container_name: filebeat
    networks:
      - xyz-network
    command: filebeat -e -strict.perms=false
    user: root
    volumes:
      - ./elk/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ./var/run/docker.sock:/var/run/docker.sock
      - xyz-volume:/var/log
    depends_on:
      - xyz-jaeger

  logstash:
    image: docker.elastic.co/logstash/logstash:7.15.1
    container_name: logstash
    ports:
      - "5044:5044"
    networks:
      - xyz-network
    depends_on:
      - filebeat
    volumes:
      - ./elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - xyz-network
    depends_on:
      - logstash

  kibana:
    image: docker.elastic.co/kibana/kibana:7.15.1
    container_name: kibana
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - xyz-network

  xyz-app:
    build: .
    container_name: xyz-app
    ports:
      - target: 5005
        published: 5005
        protocol: tcp
        mode: host
    networks:
      - xyz-network
    volumes:
      - xyz-volume:/app/log
    depends_on:
      - xyz-mysql
      - xyz-jaeger

